### ISSUE TITLE
I fail to start the cms

### ISSUE THREAD

**Issue by harryprince** [mkoistinen/staff-app-demo#6]
```
(test)HarryZhus-MacBook-Pro:src harryzhu$ sudo djangocms -p . project
Password:
Database configuration (in URL format) [default sqlite://localhost/project.db]: 
django CMS version (choices: 2.4, 3.0, 3.1, stable, develop) [default stable]: 
Django version (choices: 1.4, 1.5, 1.6, 1.7, stable) [default stable]: 
Activate Django I18N / L10N setting (choices: yes, no) [default yes]: 
Install and configure reversion support (choices: yes, no) [default yes]: 
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: en
Optional default time zone [default Asia/Harbin]: 
Activate Django timezone support (choices: yes, no) [default yes]: 
Activate CMS permission management (choices: yes, no) [default yes]: 
Use Twitter Bootstrap Theme (choices: yes, no) [default no]: 
Use custom template set [default no]: 
Load a starting page with examples after installation. Choose "no" if you use a custom template set. (choices: yes, no) [default no]: yes
Creating the project
Please wait while I install dependencies
Exception:
Traceback (most recent call last):
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 468, in get
    return self.request('GET', url, **kwargs)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 585, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 179, in resolve_redirects
    allow_redirects=False,
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='codeload.github.com', port=443): Max retries exceeded with url: /divio/djangocms-text-ckeditor/zip/master (Caused by <class 'socket.error'>: [Errno 54] Connection reset by peer)

Storing debug log for failure in /Users/harryzhu/.pip/pip.log
Failure occurred. Do you want to cleanup by removing /Users/harryzhu/BaiduPan/Github/PycharmProjects/test/src? [Y/N] 
```

**Comment by harryprince** [comment]
Why it occure this error, and I fail to find the answer.Plz help me
